[package]
name = "ml"
version = "0.1.0"
edition = "2021"

[dependencies]
compute = { path = "../compute" }
bytemuck = { version = "1.15", features = ["derive"] }
anyhow = "1.0"
physics = { path = "../physics" }
fastrand = "1.9"
